num_channels: 3
image_size: [256, 256]
learning_rate: 0.0001
ema_decay: 0.9999
horizontal_flip: True
diffuser:
  T: 1000
  linear: True
  unet:
    base_channels: 128
    num_res_attn_blocks: 2
    channel_mults: [2, 2, 2]
    is_attn: [False, True, True, False]
    num_heads: 4
    dropout: 0.1
    use_scale_shift_norm: False
